### ISSUE TITLE
[FEATURE] Play jumping animation when jumping off of a wall

### ISSUE THREAD

**Issue by selimnahimi** [selimnahimi/runnervision#78]
**Is your feature request related to a problem? Please describe.**
When jumping off of a wall, the falling animation is played instead of the jumping one.

**Describe the feature you'd like**
The solution to this is easy. Simply add `Jumping = true;` into the `InitiateJumpOffWall()` method [here](https://github.com/selimnahimi/runnervision/blob/dev-preview/code/pawn/PawnController.Util.cs).

**Additional context**
None

**Comment by nexuspy** [comment]
can I work on this?

**Comment by selimnahimi** [comment]
Yes, go ahead, thank you 🙂

**Comment by nexuspy** [comment]
can you please look after this? @selimnahimi

**Comment by selimnahimi** [comment]
After testing, it looks like this is a non-issue, but thank you for your contribution!
